module:
  hugoVersion:
    min: '0.64.0'
  mounts:
    - source: page/index.md
      target: content/simpleicons.md
      lang: en
    - source: page/template.html
      target: layouts/_default/simpleicons.html
    - source: partials
      target: layouts/partials/simple
  imports:
    - path: github.com/simple-icons/simple-icons
      mounts:
      - source: icons
        target: assets/simple-icons/icons
